export {
	type ActivityRef,
	type ActivityTransition,
	activityRef,
	type DerivedEvent,
	deriveMeaningfulEvents,
	deriveTransitions,
} from "./activities/meaningful-events";
export {
	type BrowserContext,
	buildContexts,
	CONTEXT_THRESHOLDS,
	type ContextDomain,
	type Excursion,
	getContextById,
	getContexts,
	getRecentContexts,
} from "./contexts/contexts";
export {
	advanceReadIndex,
	attachBuffer,
	availableCount,
	BUFFER_BYTE_SIZE,
	bufferOccupancy,
	CAPACITY,
	CONTROL_SLOTS,
	claimSlots,
	createBuffer,
	DEFAULT_CAPACITY,
	decodeEvent,
	EVENT_SLOT_SIZE,
	type EventBuffer,
	encodeEvent,
	PUBLISHED_INDEX,
	pushEvent,
	READ_INDEX,
	reserveSlot,
	WRITE_INDEX,
} from "./events/buffer";
export {
	bulkInsertEvents,
	countEvents,
	createEventsDb,
	getAllEvents,
	type StoredTabEvent,
	storedTabEventSchema,
} from "./events/db";
export {
	EVENT_TYPES,
	type TabEvent,
	type TabEventType,
	ValueToEventType,
} from "./events/events";
export {
	getMeta,
	removeMeta,
	type TabMeta,
	tabMeta,
	updateMeta,
} from "./events/metadata";
export { logger } from "./lib/logger";
export {
	type BufferReadyMessage,
	createEmptyStats,
	type GetEventsMessage,
	MSG,
	type PipelineStats,
	type StatsSnapshot,
	type StatsUpdateMessage,
} from "./lib/protocol";
export {
	buildMemories,
	getMemories,
	getMemoriesBySignature,
	getMemoryById,
	MEMORY_THRESHOLDS,
	type Memory,
	type MemoryDomain,
} from "./memories/memories";
export {
	buildLiveContext,
	getCurrentBrowserContext,
	getLiveInteractionIntensity,
	getLiveNavigationSequence,
	type LiveBrowserContext,
} from "./recall/live-context";
export {
	annotateTimelineCore,
	type ContextSummary,
	contextSignature,
	type DomainHistoryReport,
	findMemoryBySignature,
	findSimilarContexts,
	findSimilarContextsCore,
	findSimilarMemories,
	findSimilarMemoriesCore,
	getActivityBetween,
	getActivityTimeline,
	getActivityToday,
	getContextsWithDomain,
	getCurrentContext,
	getDomainHistory,
	getDomainsInContext,
	getMemoryHistoryForDomain,
	getPreviousContext,
	getRecentActivity,
	isDomainNovel,
	isSignatureRecurrent,
	jaccardIndex,
	type RecurrenceReport,
	reportRecurrence,
	type SimilarContextResult,
	type SimilarMemoryResult,
	summarizeContext,
	summarizeContextCore,
	type TimelineEntry,
} from "./recall/retrieval";
export {
	type DomainParticipation,
	getRecentSessions,
	getSessionById,
	getSessions,
	SESSION_THRESHOLDS,
	type Session,
	sessionize,
	type TabParticipation,
} from "./sessions/sessions";
