export {
	advanceReadIndex,
	attachBuffer,
	availableCount,
	BUFFER_BYTE_SIZE,
	bufferOccupancy,
	CAPACITY,
	CONTROL_SLOTS,
	claimSlots,
	createBuffer,
	DEFAULT_CAPACITY,
	decodeEvent,
	EVENT_SLOT_SIZE,
	type EventBuffer,
	encodeEvent,
	PUBLISHED_INDEX,
	pushEvent,
	READ_INDEX,
	reserveSlot,
	WRITE_INDEX,
} from "./buffer";
export {
	type BrowserContext,
	buildContexts,
	CONTEXT_THRESHOLDS,
	type ContextDomain,
	type Excursion,
	getContextById,
	getContexts,
	getRecentContexts,
} from "./contexts";
export {
	bulkInsertEvents,
	countEvents,
	createEventsDb,
	getAllEvents,
	type StoredTabEvent,
	storedTabEventSchema,
} from "./db";
export {
	EVENT_TYPES,
	type TabEvent,
	type TabEventType,
	ValueToEventType,
} from "./events";
export {
	buildLiveContext,
	getCurrentBrowserContext,
	getLiveInteractionIntensity,
	getLiveNavigationSequence,
	type LiveBrowserContext,
} from "./live-context";
export { logger } from "./logger";
export {
	type ActivityRef,
	type ActivityTransition,
	activityRef,
	type DerivedEvent,
	deriveMeaningfulEvents,
	deriveTransitions,
} from "./meaningful-events";
export {
	buildMemories,
	getMemories,
	getMemoriesBySignature,
	getMemoryById,
	MEMORY_THRESHOLDS,
	type Memory,
	type MemoryDomain,
} from "./memories";
export {
	getMeta,
	removeMeta,
	type TabMeta,
	tabMeta,
	updateMeta,
} from "./metadata";
export {
	type BufferReadyMessage,
	createEmptyStats,
	type GetEventsMessage,
	MSG,
	type PipelineStats,
	type StatsSnapshot,
	type StatsUpdateMessage,
} from "./protocol";
export {
	annotateTimelineCore,
	type ContextSummary,
	contextSignature,
	type DomainHistoryReport,
	findMemoryBySignature,
	findSimilarContexts,
	findSimilarContextsCore,
	findSimilarMemories,
	findSimilarMemoriesCore,
	getActivityBetween,
	getActivityTimeline,
	getActivityToday,
	getContextsWithDomain,
	getCurrentContext,
	getDomainHistory,
	getDomainsInContext,
	getMemoryHistoryForDomain,
	getPreviousContext,
	getRecentActivity,
	isDomainNovel,
	isSignatureRecurrent,
	jaccardIndex,
	type RecurrenceReport,
	reportRecurrence,
	type SimilarContextResult,
	type SimilarMemoryResult,
	summarizeContext,
	summarizeContextCore,
	type TimelineEntry,
} from "./retrieval";
export {
	type DomainParticipation,
	getRecentSessions,
	getSessionById,
	getSessions,
	SESSION_THRESHOLDS,
	type Session,
	sessionize,
	type TabParticipation,
} from "./sessions";
